/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_jocularchao_JNITest */

#ifndef _Included_top_jocularchao_JNITest
#define _Included_top_jocularchao_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_jocularchao_JNITest
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_top_jocularchao_JNITest_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
